from pathlib import Path


LOOKBACK_PERIOD = "2y"
INITIAL_CAPITAL = 100_000.0
MAX_GROSS_EXPOSURE_FRACTION = 2.0
COMMISSION_BPS_PER_LEG = 2.0
SLIPPAGE_BPS_PER_LEG = 3.0

REGRESSION_WINDOW = 60
ZSCORE_WINDOW = 30
VOL_TARGET_WINDOW = 20
HALF_LIFE_WINDOW = 60
ROLLING_CORRELATION_WINDOW = 20
STABILITY_LOOKBACK = 60
RECENT_SPREAD_VOL_WINDOW = 20
RECENT_COINTEGRATION_WINDOW = 90

ENTRY_THRESHOLD = 2.0
EXIT_THRESHOLD = 0.5
MAX_ENTRY_ZSCORE = 3.5
MAX_HALF_LIFE = 20
MAX_HOLD_DAYS = 10

MAX_SIGNAL_MULTIPLIER = 3.0
TARGET_DAILY_VOL = 0.01
SPREAD_VOL_WEIGHT_EXPONENT = 1.0
SPREAD_VOL_WEIGHT_FLOOR = 0.50

TOP_N_PAIRS = 3
MAX_PAIRS_PER_BUCKET = 1
MAX_PAIR_WEIGHT = 0.45

SOFT_PVALUE_THRESHOLD = 0.10
MIN_ABS_BETA = 0.20
MAX_ABS_BETA = 2.50
MIN_LIVE_ABS_BETA = 0.10

MIN_TEST_SHARPE = 0.25
MIN_TRAIN_SHARPE = -0.10
MIN_CORRELATION = 0.50
MIN_TRADES = 8
MIN_ROWS = 300
MIN_STABILITY_OBS = 20
MIN_RECENT_CORRELATION_MEAN = 0.45
MAX_RECENT_CORRELATION_STD = 0.20
MAX_RECENT_BETA_STD = 0.35
MAX_RECENT_SPREAD_VOL_RATIO = 1.75
ENABLE_RECENT_COINTEGRATION_CHECK = True
MAX_RECENT_COINTEGRATION_PVALUE = 0.20

EVALUATION_MODE = "split"
TRAIN_TEST_SPLIT_FRACTION = 0.70
WALK_FORWARD_TRAIN_WINDOW = 252
WALK_FORWARD_TEST_WINDOW = 63
WALK_FORWARD_STEP_WINDOW = 63

VERBOSE = False

LOG_PATH = Path("paper_trading_log.csv")
RUN_JOURNAL_PATH = Path("daily_run_journal.md")

UNIVERSE = {
    "semis": ["NVDA", "AMD", "AVGO", "QCOM", "TXN", "MU"],
    "payments": ["V", "MA", "AXP", "PYPL"],
    "oil_majors": ["XOM", "CVX", "COP", "EOG", "OXY", "SLB"],
    "banks": ["GS", "MS", "JPM", "BAC", "C", "WFC"],
    "retail": ["WMT", "TGT", "COST", "DG", "DLTR"],
    "home": ["HD", "LOW"],
    "beverages_food": ["KO", "PEP", "MNST", "KDP", "MCD", "SBUX"],
    "software": ["MSFT", "ADBE", "CRM", "ORCL", "INTU"],
}
